Repository SandroGuerotto/PrettySecureCloud, pull requests merged in 2022-05, with the labels that each got.

#48 Feature/42 authentication
  .gitignore
  configs/insert_app_file
  src/main/java/ch/psc/PrettySecureCloud.java
  src/main/java/ch/psc/datasource/JSONWriterReader.java
  src/main/java/ch/psc/datasource/SecretKeyTypeAdapterFactory.java
  src/main/java/ch/psc/domain/cipher/CipherFactory.java
  src/main/java/ch/psc/domain/cipher/KeyGenerator.java
  src/main/java/ch/psc/domain/cipher/PlainTextCipher.java
  src/main/java/ch/psc/domain/cipher/PscCipher.java
  src/main/java/ch/psc/domain/cipher/SecretKeySerialization.java
  src/main/java/ch/psc/domain/cipher/SecurityLevel.java
  src/main/java/ch/psc/domain/common/context/AuthenticationContext.java
  src/main/java/ch/psc/domain/common/context/UserContext.java
  src/main/java/ch/psc/domain/error/FatalImplementationException.java
  src/main/java/ch/psc/domain/storage/StorageManager.java
  src/main/java/ch/psc/domain/storage/service/DropBoxService.java
  src/main/java/ch/psc/domain/storage/service/LocalStorage.java
  src/main/java/ch/psc/domain/user/AuthenticationService.java
  src/main/java/ch/psc/domain/user/JSONAuthenticationService.java
  src/main/java/ch/psc/domain/user/User.java
  src/main/java/ch/psc/exceptions/AuthenticationException.java
  src/main/java/ch/psc/exceptions/ScreenSwitchException.java
  src/main/java/ch/psc/exceptions/UpdateUserException.java
  src/main/java/ch/psc/gui/Config.java
  src/main/java/ch/psc/gui/FileBrowserController.java
  src/main/java/ch/psc/gui/LoginController.java
  src/main/java/ch/psc/gui/SignUpController.java
  src/main/java/ch/psc/gui/components/signUp/ChooseEncryption.java
  src/main/java/ch/psc/gui/components/signUp/ChooseStorageService.java
  src/main/java/ch/psc/gui/components/signUp/CreateAccount.java
  src/main/java/ch/psc/gui/components/signUp/SignUpFlowControl.java
  src/main/java/ch/psc/gui/util/JavaFxUtils.java
  src/main/resources/ch/psc/gui/signUp.fxml
  src/test/java/ch/psc/datasource/JSONWriterReaderTest.java
  src/test/java/ch/psc/domain/cipher/CipherTest.java
  src/test/java/ch/psc/domain/storage/service/DropBoxServiceTest.java
  src/test/java/ch/psc/domain/user/JSONAuthenticationServiceTest.java
  users/empty
Labels: feature

#53 Possibility to generate asymmetric key pair
  src/main/java/ch/psc/domain/cipher/AesCipher.java
  src/main/java/ch/psc/domain/cipher/CipherAlgorithms.java
  src/main/java/ch/psc/domain/cipher/Key.java
  src/main/java/ch/psc/domain/cipher/KeyGenerator.java
  src/main/java/ch/psc/domain/cipher/PlainTextCipher.java
  src/main/java/ch/psc/domain/cipher/PscCipher.java
  src/main/java/ch/psc/domain/cipher/RsaCipher.java
  src/main/java/ch/psc/domain/cipher/SecurityLevel.java
  src/main/java/ch/psc/domain/file/EncryptionState.java
Labels: feature

#65 LocalStorage Downlaod implementation
  src/main/java/ch/psc/domain/storage/service/LocalStorage.java
Labels: feature

#69 FileBrowser / Up-download
  build.gradle
  src/main/java/ch/psc/PrettySecureCloud.java
  src/main/java/ch/psc/datasource/datastructure/Tree.java
  src/main/java/ch/psc/domain/cipher/PscCipher.java
  src/main/java/ch/psc/domain/file/PscFile.java
  src/main/java/ch/psc/domain/storage/ProcessEvent.java
  src/main/java/ch/psc/domain/storage/StorageManager.java
  src/main/java/ch/psc/domain/storage/service/CloudService.java
  src/main/java/ch/psc/domain/storage/service/DropBoxService.java
  src/main/java/ch/psc/domain/storage/service/FileStorage.java
  src/main/java/ch/psc/domain/storage/service/GoogleDriveService.java
  src/main/java/ch/psc/domain/storage/service/LocalStorage.java
  src/main/java/ch/psc/domain/storage/service/StorageService.java
  src/main/java/ch/psc/domain/storage/service/StorageServiceFactory.java
  src/main/java/ch/psc/domain/user/JSONAuthenticationService.java
  src/main/java/ch/psc/domain/user/User.java
  src/main/java/ch/psc/exceptions/ScreenSwitchException.java
  src/main/java/ch/psc/gui/FileBrowserController.java
  src/main/java/ch/psc/gui/LoginController.java
  src/main/java/ch/psc/gui/SignUpController.java
  src/main/java/ch/psc/gui/components/FileBrowserTable.java
  src/main/java/ch/psc/gui/components/fileBrowser/FileBrowserTreeTableView.java
  src/main/java/ch/psc/gui/components/fileBrowser/FileRow.java
  src/main/java/ch/psc/gui/components/signUp/ChooseStorageService.java
  src/main/java/ch/psc/gui/util/JavaFxUtils.java
  src/main/resources/ch/psc/gui/fileBrowser.fxml
  src/main/resources/ch/psc/gui/styles.css
  src/main/resources/images/fileBrowser/computer.png
  src/main/resources/images/fileBrowser/folder-open.png
  src/main/resources/images/fileBrowser/folder.png
  src/main/resources/images/fileBrowser/text-x-generic.png
  src/main/resources/images/local/icon.png
  src/main/resources/text.properties
  src/test/java/ch/psc/datasource/JSONWriterReaderTest.java
  src/test/java/ch/psc/domain/cipher/AesCipherTest.java
  src/test/java/ch/psc/domain/cipher/CipherTest.java
  src/test/java/ch/psc/domain/cipher/PlainTextCipherTest.java
  src/test/java/ch/psc/domain/cipher/RsaCipherTest.java
  src/test/java/ch/psc/domain/storage/service/DropBoxServiceTest.java
  src/test/java/ch/psc/domain/user/JSONAuthenticationServiceTest.java
Labels: feature, refactoring

#71 Feature/62 localstorage file tree
  src/main/java/ch/psc/domain/storage/service/LocalStorage.java
  src/main/java/ch/psc/gui/components/signUp/ChooseStorageService.java
Labels: feature

#73 Feature/72 errorlabels signup login
  src/main/java/ch/psc/domain/user/JSONAuthenticationService.java
  src/main/java/ch/psc/gui/LoginController.java
  src/main/java/ch/psc/gui/SignUpController.java
  src/main/java/ch/psc/gui/components/validator/EmailValidator.java
  src/main/resources/ch/psc/gui/styles.css
  src/main/resources/text.properties
Labels: feature, refactoring

#81 GUI Test Cases
  doc/PSC_GUI_TestCases_V_1.0.0.0.xlsx
Labels: documentation

#84 Hotfixes for V0.1
  src/main/java/ch/psc/domain/storage/StorageManager.java
Labels: bug

#86 added all documents
  doc/M1_Projektskizze/Projektskizze.pdf
  doc/M1_Projektskizze/Präsentation_M1.pdf
  doc/M2_Technischer_Bericht_I/Praesentation_M2.pdf
  doc/M2_Technischer_Bericht_I/Technischer_Bericht_I.pdf
  doc/M3_Technischer_Bericht_II/Praesentation_M3.pdf
  doc/M3_Technischer_Bericht_II/Technischer_Bericht_II.pdf
Labels: documentation

#88 Version 0.1 documents
  doc/M1_Projektskizze/Projektskizze.pdf
  doc/M1_Projektskizze/Präsentation_M1.pdf
  doc/M2_Technischer_Bericht_I/Praesentation_M2.pdf
  doc/M2_Technischer_Bericht_I/Technischer_Bericht_I.pdf
  doc/M3_Technischer_Bericht_II/Praesentation_M3.pdf
  doc/M3_Technischer_Bericht_II/Technischer_Bericht_II.pdf
Labels: documentation
